language: node_js
sudo: false

node_js:
    - "node"

cache:
    apt: true
    directories:
        # cache for all npm packages needed
        - $(npm config get prefix)/bin/gulp
        - node_modules

before_script:
    - npm install -g bower
    - bower install
    - npm run gulp &
    - sleep 2
    - ./node_modules/protractor/bin/webdriver-manager update

script:
    # run unit tests with gulp
    - npm run test
    # start xvbfb, required for e2e tests
    - Xvfb :99 &
    - export DISPLAY=:99
    - sleep 5 # give xvfb some time to start
    # start the webdriver and run e2e tests with protractor
    - ( ./e2e_tests/node_modules/protractor/bin/webdriver-manager start &> /tmp/selenium.log ) & (sleep 10 && gulp e2e_tests && sleep 5 )
