language: node_js
sudo: required
dist: trusty
node_js:
    - "4.3.1"

addons:
    apt:
        sources:
            - google-chrome
    packages:
        - unzip
        - google-chrome-stable

cache:
    apt: true
    directories:
        # cache for all npm packages needed
        - $(npm config get prefix)/bin/gulp
        - node_modules
        - bower_components

before_install:
    - export CHROME_BIN=/usr/bin/google-chrome
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

    # Install Chrome driver
    - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/bin/

before_script:
    - ls
    - npm install -g bower webdriver-manager protractor
    - bower install
    - sleep 10

script:
    - npm run test
