language: node_js
sudo: false

node_js:
    - "node"

cache:
    apt: true
    directories:
        # cache for all npm packages needed
        - $(npm config get prefix)/bin/gulp
        - node_modules

before_script:
    - npm install -g bower
    - bower install
    - node_modules/protractor/bin/webdriver-manager update

script:
    - Xvfb :99 &
    - export DISPLAY=:99
    - sleep 10 # give xvfb some time to start
    # start the webdriver and run e2e tests with protractor
    - npm run gulp & npm run test
