language: node_js
sudo: true
node_js:
    - "4.3.1"

addons:
  packages:
    - unzip
    - google-chrome-stable

cache:
    apt: true
    directories:
        # cache for all npm packages needed
        - $(npm config get prefix)/bin/gulp
        - node_modules

before_install:
    # Install Chrome driver
    - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/bin/

    # For selenium in headless linux system, But no need when PhantomJS
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

before_script:
    - ls & sleep 50
    - npm install -g bower webdriver-manager
    - bower install
    - webdriver-manager update

script:
    # start xvbfb, required for e2e tests
    - Xvfb :99 &
    - export DISPLAY=:99
    - sleep 5 # give xvfb some time to start
    # start the webdriver and run e2e tests with protractor
    - (npm run webdriver-manager start &> /tmp/selenium.log ) & (sleep 10 && npm run gulp & npm run test && sleep 5 )
