language: node_js
sudo: false
node_js:
    - "4.3.1"

cache:
    apt: true
    directories:
        # cache for all npm packages needed
        - $(npm config get prefix)/bin/gulp
        - node_modules

before_script:
    - ls & sleep 50
    - npm install -g bower webdriver-manager
    - bower install
    - webdriver-manager update

script:
    # start xvbfb, required for e2e tests
    - Xvfb :99 &
    - export DISPLAY=:99
    - sleep 5 # give xvfb some time to start
    # start the webdriver and run e2e tests with protractor
    - (npm run webdriver-manager start &> /tmp/selenium.log ) & (sleep 10 && npm run gulp & npm run test && sleep 5 )
